# Generated by Django 3.2.6 on 2021-08-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='best_race_finish',
            field=models.PositiveSmallIntegerField(default=None, help_text='Самая высокая позиция занятая в гонке', null=True, verbose_name='Best race finish'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='highest_grid_position',
            field=models.PositiveSmallIntegerField(default=None, help_text='Самая высокая занятая позиция в квалификации', null=True, verbose_name='Highest grid position'),
        ),
    ]
