# Generated by Django 3.2.6 on 2021-08-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_league', '0002_auto_20210824_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='image',
            field=models.ImageField(default=None, help_text='Аватарка пилота', max_length=200, null=True, upload_to='assets/images/pilots', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='league',
            field=models.PositiveSmallIntegerField(default=2, help_text='Номер лиги, в которой выступает пилот', verbose_name='League'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='name',
            field=models.CharField(default='', help_text='Имя пилота', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='race',
            name='country',
            field=models.CharField(default='', help_text='Страна, в которой проходит гонка', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='race',
            name='country_flag',
            field=models.ImageField(default=None, help_text='Флаг страны', max_length=200, null=True, upload_to='assets/images/flags', verbose_name='Country flag'),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(default='', help_text='Название гоночной трассы', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default=None, help_text='Картинка команды', max_length=200, null=True, upload_to='assets/images/teams', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='', help_text='Название команды', max_length=50, verbose_name='Name'),
        ),
    ]
