# Generated by Django 3.2.6 on 2021-08-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_league', '0003_auto_20210824_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='number_of_races_completed',
            field=models.PositiveSmallIntegerField(default=0, help_text='Количество пройдённых гонок в сезоне', verbose_name='Number of races completed'),
        ),
    ]
