# Generated by Django 3.2.6 on 2021-08-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_league', '0005_auto_20210826_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='url_name',
            field=models.CharField(default='', help_text='Адрес url', max_length=50, verbose_name='Url name'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='image',
            field=models.ImageField(default=None, help_text='Аватарка пилота', max_length=200, null=True, upload_to='../assets/images/pilots', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='race',
            name='country_flag',
            field=models.ImageField(default=None, help_text='Флаг страны', max_length=200, null=True, upload_to='../assets/images/flags', verbose_name='Country flag'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(default=None, help_text='Картинка команды', max_length=200, null=True, upload_to='../assets/images/teams', verbose_name='Image'),
        ),
    ]
