# Generated by Django 3.2.6 on 2021-08-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_league', '0006_auto_20210829_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='url_name',
            field=models.CharField(default='', help_text='Адрес url', max_length=50, unique=True, verbose_name='Url name'),
        ),
    ]
