# Generated by Django 3.2.6 on 2021-08-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_league', '0007_alter_team_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='place_in_calendar',
            field=models.PositiveSmallIntegerField(default=None, help_text='Позиция трассы в календаре', verbose_name='Place in calendar'),
        ),
    ]
