# Generated by Django 3.2.6 on 2021-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_league', '0009_alter_race_place_in_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='place_in_calendar',
            field=models.PositiveSmallIntegerField(default=0, help_text='Позиция трассы в календаре', verbose_name='Place in calendar'),
        ),
    ]
