# Generated by Django 3.2.6 on 2021-09-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_league', '0010_alter_race_place_in_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='penalties',
        ),
        migrations.AddField(
            model_name='result',
            name='is_result_of_reserve_pilot',
            field=models.BooleanField(default=False, help_text='Принадлежит ли этот результат резервному пилоту', verbose_name='Is result of reserve pilot'),
        ),
    ]
