# Generated by Django 3.2.6 on 2021-09-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_league', '0012_result_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='team_id',
            field=models.PositiveSmallIntegerField(default=None, help_text='ID команды, к которой относится данный результат', null=True, verbose_name='Team id'),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='total_score',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Количество очков в личном зачёте', max_digits=5, verbose_name='Total score'),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Количество заработанных очков в гонке', max_digits=5, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_score_league1',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Количество очков в кубке конструкторов лиги 1', max_digits=5, verbose_name='Total score league 1'),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_score_league2',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Количество очков в кубке конструкторов лиги 1', max_digits=5, verbose_name='Total score league 2'),
        ),
    ]
